name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: {{ cookiecutter.min_python_version }}
        architecture: x64
    - run: pip install nox==2024.3.2
    - run: nox
