name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: {{ cookiecutter.min_python_version }}
        architecture: x64
    - run: pip install nox==2022.1.7
    - run: pip install poetry==1.1.3
    - run: pip install pytest==7.1.2
    - run: pip install flake8==4.0.1
    - run: pip install mypy==0.960
    - run: pip install coverage==6.4
    - run: pip install pytest-cov==3.0.0
    - run: nox
